apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blogdemo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: blogdemo
    kind: SecretStore
  target:
    name: blogdemosecret
    creationPolicy: Owner
  data:
  - secretKey: admin-posgres-username
    remoteRef:
      key: test/test/test #AWS Secrets Manager secret name
      property: username #AWS Secrets Manager secret key
  - secretKey: admin-posgres-password
    remoteRef:
      key: test/test/test #AWS Secrets Manager secret name
      property: password #AWS Secrets Manager secret key