apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: BLOG_SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: blogdemosecret
            key: admin-posgres-username
            optional: false 
      - name: BLOG_SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: blogdemosecret
            key: admin-posgres-password
            optional: false
  restartPolicy: Always